spring.config.import=optional:dotenv
spring.application.name=PetStore

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# To test the graphQL endpoint
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql